[package]
name = "trinity"
version = "0.1.0"
edition = "2021"
authors = ["Dyson Dyson <dyson.dyson@icloud.com>"]
repository = "https://github.com/DoctorDalek1963/winter-wonderlights"
license = "AGPL-3.0-only"
publish = false

[dependencies]
